{% set version = '0.2.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-purrr
  version: {{ version|replace("-", "_") }}

source:
  fn: purrr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/purrr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/purrr/purrr_{{ version }}.tar.gz
  sha256: ed8d0f69d29b95c2289ae52be08a0e65f8171abb6d2587de7b57328bf3b2eb71


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, dplyr (>= 0.4.3), knitr, rmarkdown, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make

  host:
    - r-base
    - r-magrittr >=1.5
    - r-rlang >=0.1
    - r-tibble

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-magrittr >=1.5
    - r-rlang >=0.1
    - r-tibble

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('purrr')"           # [not win]
    - "\"%R%\" -e \"library('purrr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://purrr.tidyverse.org, https://github.com/tidyverse/purrr
  license: GPL-3 | file LICENSE
  summary: A complete and consistent functional programming toolkit for R.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: purrr
# Title: Functional Programming Tools
# Version: 0.2.4
# Authors@R: c( person("Lionel", "Henry", , "lionel@rstudio.com", c("aut", "cre")), person("Hadley", "Wickham", , "hadley@rstudio.com", "aut"), person("RStudio", role = c("cph", "fnd")) )
# Description: A complete and consistent functional programming toolkit for R.
# License: GPL-3 | file LICENSE
# URL: http://purrr.tidyverse.org, https://github.com/tidyverse/purrr
# BugReports: https://github.com/tidyverse/purrr/issues
# Depends: R (>= 3.1)
# Imports: magrittr (>= 1.5), rlang (>= 0.1), tibble
# Suggests: covr, dplyr (>= 0.4.3), knitr, rmarkdown, testthat
# VignetteBuilder: knitr
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-10-18 13:06:58 UTC; hadley
# Author: Lionel Henry [aut, cre], Hadley Wickham [aut], RStudio [cph, fnd]
# Maintainer: Lionel Henry <lionel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-10-18 20:19:51 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
