travis:
  secure:
    BINSTAR_TOKEN: 1bOFyjGc3jlWZ/Ov9LzXduHHjOZtVxR1XhLF7DnCWsNPFQbuIsIQT5+iZ8+vZ2pLg+gIXP3JKZR3wQ5HveE9Ycbab0gLdK9SWRA3hWqp6QqNjGU4B5Qk3dlVzhffL1NHC/Cyuw7JfiW20vQu2qWBUDN8luV8eHlQwXZo5abYLt+Y14Vk6ZvLSt/ZWLHRc/8V1fOqLiJb93X8dK8J/KxEYLMOKTIYsmoRdBTRVrEm1Ug8rDB9y8vKYGT3dttxUS8+uHrlsfYjUjW/gGXBMSkFtC82LUfWqgz7GZ9Q+asZP1Lt+c+ya+msnusm2Y5ZQGG7VsVYs+5NebpQ1KWGYcIbBozJVoVDIdPLHHQ1XOpGwqb5Ci8iaCvvISRs4uZro2KqcjF/ovlqAKmyU5Q1TqQucSTgkT7P3UNun52q/ZyGMdobUu6Lfmq+s0pntzySXd48sIbqIAQr7RB4tbCOSFa15U0gZGYD5cALQFe2StOCh6J0VRUw5loyPly8yNJnyvFelz1WRJjLWhBoO4oKYPuaR0D7GZNYBcLgaNg57Pwdr8yBFdfzLQUp6ilGbo6WKyevaLT9ptw/1Dm+40YjvFxRv27J6bPuRdjmYWivFF7AJWRzWOCmLgsq80QTePQU4wD2IMZ6n0IONKrvxuWhC4wqHYbDwinxMeOYczg6dnMc4rw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
