travis:
  secure:
    BINSTAR_TOKEN: N2+mjb6Nf4Qrqdoxvog8vG31fm9ghM3Ua0u6sMXB7l/eYfIPA4MZc6HrDW5Wpd++QTUo9HdOiAa5CaC/u99uXClBWuK5WQu/p/9tlD/+rOUec1fqa4qEP9+4kBXw4N4dSa24qHW+l6EXMKTaYBhW1+na9nx28qzFxymwbo+dENKO1MxzSnRsu0Irzu2OeSu7eMNiJdlKxEwjB2Nad5yiHIDD5eeYfcXzeVwY1rnwKSEqmy8ACREoT421FT6sp6xU+mS8mn3Qd0x1PJKoH9WP59kyYYjMMw9P0CnEQE0W1k3o3DsznNqYmvbIpSLo+AFASHwewc2MpyuXK4vFjN24N/ehlKcvWz5oBjj5sY6UCJB07ScuprZy8o/lHMcD8+vtGxgiyGUuAWKTkl85cgWYZdAj8yfUeyA9wfWwqa5MHeZieTKkjotjT/VG/tjBwDDI+j+XElqnXwchM3Ng6O3472CdNeNhH/gLK1zi+eFbUi4QR36TX3ud2AA5rWIaWEkLEVMtVZih8kNsegIi7ycBWTGBjgeJ3RUpFstf27SVLp2BOm7WjIX0PQjTCCmVB2tTvdCthdHoyX/oknlZ+HZRWOFwOLbo0qrWYO0X22N1bhxuuuQVNMqBLu0KFR7X4kUa9CXI8N6wlmPt0jvewdurwjR07aQgrlPGvgVmgFKQ/As=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
