travis:
  secure:
    BINSTAR_TOKEN: bUgTVaFUOaM3rPh8pphTaxwY1Gpd1XPcrOtvk7ZSRr92esGKfd2b98PqIdkbrIz4q930B1g49J23B13z/3HrABNbcLse7uIHA7VRmCpN7Nd1AThWclGGIjyMuBiDYUTia1UZsR0M2We0DRsRbhpQ834QSy2yjQL88RFOHgblmy8ECHENEPdAqnESpyTFfY4F0BEGgnFtS9M2kxqp6ZBwif5Pmw6QEd/nPdsPcQyg172GlYsFJgVASyHHQWf8HhKCFFIfrIq43+ljtipff1vSjjL2XRO0+Ymd8Kqteab6GKehw6t0mRzpFE3rM1v8GXmgey72TgR4uDY3aPcEfzRN/tAYqk3F9T087abOIl2IuUFDCdfz8DI/JEc80Q/yt08eMr/PG4dHsUYSVs4M8SJ9PgFqaRRGVhmdSgLarTD7PHFUm9CyQD6fOR2NTdaUVpjMXL/u5CvKULlKQCTRcOQds6GhkUzEyPKoTnmOiQHcS9A4UZwU6TWs7EuVAPeaelfAwd28M5eP9R/frhs9o4dyxsFnbFOCDe1TlKfZYxk6He46hFlkMO5WOt34Am+tKe3OdKAGFSLW6Mc/l+VLb72ikc7WgDJpxA8On39CZLRORGi3eBEnM7rmTfssJ32/hZx1LyzeCql/zjXnCWJjRzEeI9vu8tJ9ooIo+KfCS6ssHmo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
